name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Install and Build
      run: |
        npm ci
        npx webpack
    - name: Upload bundles.js artifact
      uses: actions/upload-artifact@v4
      with:
        name: bundle-js-file
        path: bundle.js

  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner
    runs-on: ubuntu-latest
    steps:
    # Download bundles-file artifact
      - name: Download bundle.js artifact
        uses: actions/download-artifact@v4
        with: 
          name: bundle-js-file
    # Extract various metadata
      - name: Configure Pages
        uses: actions/configure-pages@v1
    # Upload pages artifact
      - uses: actions/upload-pages-artifact@v1
        with:
          path: .
    # Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      
